# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20171211_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='shadowexpire',
            field=models.CharField(max_length=20),
        ),
    ]
