# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20171211_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='forwardedmail',
        ),
    ]
