# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_userprofile_forwardedmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telephoneNumber',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userPassword',
        ),
    ]
